name = "socolive"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "socolive-db"
database_id = "d086f4f3-321a-457c-a171-fda2354efed6"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "socolive-images"
